#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this data.
awk '
  NF >= 9 && $9 ~ /^[0-9]+$/ {
    key = $1 " " $9
    count[key]++
  }
  END {
    for (k in count)
      print count[k], k
  }
' apache-access.log | sort -nr

