#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this data.
awk '
  {
    if (NF < 9) next
    key = $1 " " $9
    count[key]++
  }
  END {
    for (k in count)
      print count[k], k
  }
' apache-access.log | sort -nr

