#!/usr/bin/env bash
# The script displays Process and PID file
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'sudo rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done

