#!/usr/bin/env bash
# The script manages process
case "$1" in
    start)
        ./manage_my_process &
        pid=$!
        echo "$pid" | sudo tee /var/run/my_process.pid > /dev/null
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill "$pid"
            sudo rm -f /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        "$0" stop
        "$0" start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

