#!/usr/bin/env bash
# The script is displaying the PID, along with the process name, of processes whose name contain the word bash.
for pid in /proc/[0-9]*; do
  name=$(cat "$pid/comm" 2>/dev/null)
  if [[ $name == *bash* ]]; then
    echo "$(basename "$pid") $name"
  fi
done

