#!/usr/bin/env bash
# The script stops 4-to_infinity_and_beyond process.
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
  echo "Stopping 4-to_infinity_and_beyond (PID: $pid)..."
  pkill -f "4-to_infinity_and_beyond"
else
  echo "Process not found."
fi

