#!/usr/bin/env bash
# The script stops 4-to_infinity_and_beyond process.
for pid in /proc/[0-9]*; do
  name=$(cat "$pid/comm" 2>/dev/null)
  if [[ "$name" == "4-to_infinity_and_beyond" ]]; then
    exit 0
  fi
done

