#!/usr/bin/env bash
# The script stops 4-to_infinity_and_beyond process.
pid=$(ps -eo pid,cmd | grep "[4]-to_infinity_and_beyond" | awk '{print $1}')
[ -n "$pid" ] && xargs -r -n1 < <(echo "$pid") /bin/kill

